name: iic
channels:
    - defaults
    - anaconda
    - conda-forge
    - pytorch
dependencies:
    - python=3.7.6
    - pyyaml=5.2
    - scikit-image=0.16.2
    - scikit-learn=0.22.1
    - tqdm=4.42.0
    - pytorch=1.4.0
    - torchvision=0.5.0
    - pip=19.3.1
    - pip:
          - opencv-python==4.1.2.30
          - libtiff==0.4.2
